Save "siteInfo" attributes in a new target
USGS-R/ds-pipelines-targets-example-wqp pull request #102
Opened 2022-12-23 21:24 UTC by lekoenig

This PR grabs the `siteInfo` attribute from each branch of `p2_wqp_data_aoi` to create a new target called `p2_wqp_site_info`. The site metadata attribute does not get retained when `p2_wqp_data_aoi` is built by binding the individual branches, and so the new site info target contains a table that users can reference or join with the data table if they wish.

As of the last time I built `p2_wqp_data_aoi`, we downloaded data from 552 sites within our example "watershed" and so `p2_wqp_site_info` contains site metadata for 552 sites: 
 ```r
tar_load(p2_wqp_data_aoi)
length(unique(p2_wqp_data_aoi$MonitoringLocationIdentifier))
[1] 552
tar_load(p2_wqp_site_info)
dim(p2_wqp_site_info)
[1] 552  43
names(p2_wqp_site_info)
 [1] "station_nm"                                      "agency_cd"                                       "site_no"                                        
 [4] "dec_lat_va"                                      "dec_lon_va"                                      "hucCd"                                          
 [7] "OrganizationIdentifier"                          "OrganizationFormalName"                          "MonitoringLocationIdentifier"                   
[10] "MonitoringLocationName"                          "MonitoringLocationTypeName"                      "MonitoringLocationDescriptionText"              
[13] "HUCEightDigitCode"                               "DrainageAreaMeasure.MeasureValue"                "DrainageAreaMeasure.MeasureUnitCode"            
[16] "ContributingDrainageAreaMeasure.MeasureValue"    "ContributingDrainageAreaMeasure.MeasureUnitCode" "LatitudeMeasure"                                
[19] "LongitudeMeasure"                                "SourceMapScaleNumeric"                           "HorizontalAccuracyMeasure.MeasureValue"         
[22] "HorizontalAccuracyMeasure.MeasureUnitCode"       "HorizontalCollectionMethodName"                  "HorizontalCoordinateReferenceSystemDatumName"   
[25] "VerticalMeasure.MeasureValue"                    "VerticalMeasure.MeasureUnitCode"                 "VerticalAccuracyMeasure.MeasureValue"           
[28] "VerticalAccuracyMeasure.MeasureUnitCode"         "VerticalCollectionMethodName"                    "VerticalCoordinateReferenceSystemDatumName"     
[31] "CountryCode"                                     "StateCode"                                       "CountyCode"                                     
[34] "AquiferName"                                     "LocalAqfrName"                                   "FormationTypeText"                              
[37] "AquiferTypeName"                                 "ConstructionDateText"                            "WellDepthMeasure.MeasureValue"                  
[40] "WellDepthMeasure.MeasureUnitCode"                "WellHoleDepthMeasure.MeasureValue"               "WellHoleDepthMeasure.MeasureUnitCode"           
[43] "ProviderName"                                   
>
```

Closes #95

2023-01-30 15:10 UTC, lindsayplatt reviewed
I like this approach because it doesn't require additional queries to WQP and I think this works really well for the small example here (which likely covers most use-cases for WQP downloads). 

However, I want to mention this might not scale well. In order to get this code to work on a national scale, I had to save intermediate files rather than have all data saved in a single `p2_wqp_data_aoi` target to avoid memory allocation failures. If you save as anything other than `rds` or `qs`, the `attr` component gets dropped and if you do use `rds`/`qs` for intermediate files, you would need to do a lot of i/o to get these attributes. So, I would recommend using the `service='Station'` argument in order to query for site metadata separately:

```r
dataRetrieval::readWQPdata(
  siteid = "USGS-04024315",
  service = "Station"
)
```

I don't find that it is an obvious feature of dataRetrieval, but you can see the base URLs listed under `How to Generate Web Services Requests` [here in the web services documentation](https://www.waterqualitydata.us/webservices_documentation/).

2023-01-30 15:15 UTC, lindsayplatt commented
With this, I will say that the actual data frame returned appears to be missing 6 of the columns that are contained in the `siteInfo` field. So, we could grab `siteInfo` from the new query instead:

```r
station_data <- dataRetrieval::readWQPdata(
  siteid = "USGS-04024315",
  service = "Station"
)

siteInfo <- attr(station_data, 'siteInfo')

sum(!names(station_data) %in% names(siteInfo))
sum(!names(siteInfo) %in% names(station_data))

names(siteInfo)[!names(siteInfo) %in% names(station_data)]

[1] "station_nm" "agency_cd"  "site_no"    "dec_lat_va" "dec_lon_va" "hucCd"
```

2023-01-30 16:17 UTC, lindsayplatt commented
I like the idea of using `ignore_attributes = TRUE` in the WQP data call. It may cut down on some of the file sizes for those big pulls.

2023-01-30 17:05 UTC, lindsayplatt requested changes
I think this is great and almost there! One issue I see is that we have this setup so that we are potentially querying sites for their info more than once.

2023-01-30 19:10 UTC, lekoenig commented on 2_download.R
> +    pattern = map(p2_site_counts_grouped)
Great idea, I've added a new target in b7ec397a9157435acbf3d54023ca1aa50143de06 to reduce redundant sites and assign download groups based on some user-defined value for `max_sites` (I started with `max_sites = 500`).

2023-02-06 15:13 UTC, lindsayplatt approved these changes
This works for me locally & I think it will scale well for folks constructing bigger WQP pulls. I've added one small comment that you can address or not.

2023-02-06 17:17 UTC, lekoenig commented on 2_download/src/fetch_wqp_site_info.R
> +    ungroup()
Great catch! I think I originally set this up as a grouped data frame, but then opted to do the grouping within `tar_targets`. I've adopted this suggestion to replace `group_by() --> ungroup()` with `mutate`.

2023-02-06 17:26 UTC, merged