Define spatial AOI for example WQP data pull
USGS-R/ds-pipelines-targets-example-wqp pull request #13
Opened 2022-03-18 20:33 UTC by lekoenig

Addresses #11.

Here I've defined our area of interest as a simple triangle polygon that might represent a watershed or bounding box. The code changes represent the following steps:

- add vectors containing the input coordinates within `_targets.R`
- use the input coordinates to create a data frame in `p1_AOI`. This target isn't really necessary, but I've added it to document/show where a user could read in a list of coordinates instead
- create an sf object that represents our area of interest

We had previously considered using a watershed shapefile to define our spatial domain, and I expect many users might be interested in doing that. Here we've opted for a simpler scheme to hopefully make this repo more maintainable, so I added some text in the README that shows how you could replace the existing targets with targets that download and/or read in an external shapefile.

Here's a preview of our example AOI:

![AOI](https://user-images.githubusercontent.com/8785034/159079109-ac1a9fef-1771-4d6f-9812-bbb44d697c41.png)

2022-03-18 20:35 UTC, lekoenig commented on README.md
> +                mode = "wb", quiet = TRUE),
Should I include the `download_file` function either in `1_fetch/src` or as code within the README? I didn't want to fill the README with too many tangential details, but I'm not sure how intuitive the idea of this function would be for folks interested in creating these targets.

2022-03-21 14:20 UTC, lindsayplatt requested changes
Just one comment related to something that _must_ change - the rogue `source()` call. I get an error when I try to run `tar_make()` since that file was not checked in. Other than that, the pipeline runs well and other comments are just suggestions!

2022-03-21 15:35 UTC, lekoenig commented on 1_fetch.R
> +source('scratch/download_file.R')
Ah, good catch! I must have added in that call to `source()` to make sure my README example worked and forgot to remove it. At least for now, I don't anticipate using `download_file()` within this repo so I've opted to remove it.

2022-03-21 15:38 UTC, lekoenig commented
Thanks for your review, @lindsayplatt! I've incorporated your requested changes and suggestions.

2022-03-21 18:58 UTC, merged